#include<stdio.h>
int main(){
    int x,i=0;
    char roman[20];
    printf("Enter a number:");
    scanf("%d",&x);
     x1000:
    if(X>=1000)
    {
        X=X-1000;
        roman[i]=M;
        i++;
        goto x1000;
    }
    else{
           if(x>=900)
           {
              x=x-900;
              roman[i]=C;
              i++;
              roman[i]=M;
              i++;
           } 
           if(x>=800)
           {
             x=x-800;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;
               roman[i]=C;
              i++;
               roman[i]=C;
              i++; 
            }
            if(x>=700)
           {
             x=x-700;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;
               roman[i]=C;
              i++;    
            }
            if(x>=600)
           {
             x=x-600;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;   
            }
           if(x>=500)
           {
            x=x-500;
            roman[i]=D;
            i++;
           }
           if(x>=400)
           {
             x=x-400;
              roman[i]=C;
              i++;
              roman[i]=D;
              i++;
            
            }
            if(x>=300)
           {
             x=x-800;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;
               roman[i]=C;
              i++;
            }
             if(x>=300)
           {
             x=x-800;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;
               roman[i]=C;
              i++;
            }
             if(x>=300)
           {
             x=x-800;
              roman[i]=D;
              i++;
              roman[i]=C;
              i++;
               roman[i]=C;
              i++;
            }
    }

}